version: '3.9'
services:
  serverless_docker:
    # Look for a Dockerfile at the the root
    build: .
    image: gabrielvini27/serverless_docker
    # These are the environment variables that are used by the api
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    volumes:
      - ./container_mnt:/mnt
secrets:
  aws_access_key_id:
    file: ./credentials/aws_access_key_id.txt
  aws_secret_access_key:
    file: ./credentials/aws_secret_access_key.txt
  